version: "3.7"

services:
  server:
    image: fjortegan/nginx-fpm
    ports:
      - "80:80"
    volumes:
      - ./parte2:/usr/share/nginx/html
    links:
      - fpm

  fpm:
    image: fjortegan/php-xdebug
    volumes:
      - ./parte2:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /bin/bash -c "apt-get update && apt-get install -y \
      && docker-php-ext-install mysqli \
      && docker-php-ext-enable mysqli \
      && php-fpm"

  db:
      image: mysql
      command: --default-authentication-plugin=caching_sha2_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: user
        MYSQL_DATABASE: quizz-app
        MYSQL_USER: user
        MYSQL_PASSWORD: user
      ports:
        - "3306:3306"
      volumes:
        - ./initSQL:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1